### ISSUE TITLE
Rstep parameter clarification

### ISSUE THREAD

**Issue by sebastianochiari** [crowdflowTUe/MF_landing_data_analysis#1]
Hi there,
I am going to use your dataset for a thesis project on the Social Force Model, but I can't understand what exactly the `Rstep` parameter represents. Can you help me?
Thank you so much

**Comment by acorbe** [comment]
Dear Sebastiano,

Apologies, I missed your message. 

Rstep counts the time steps from the beginning of a trajectories. Consider that the sampling is at 15hz and that all trajectories here are independent. 

Hope this helps 

Alessandro
